services:
  auth-server:
    build: 
      context: .
      dockerfile: auth/Dockerfile
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_CHANNEL_ID=${TWITCH_CHANNEL_ID}
      - TWITCH_CHANNEL_NAME=${TWITCH_CHANNEL_NAME}
      - TOKEN_DB_PATH=/data/tokens.db
      - TWITCH_REDIRECT_URI=${TWITCH_REDIRECT_URI}
      - PORT=8080
    volumes:
      - tokens-data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  twitch-bot:
    build: .
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_CHANNEL_ID=${TWITCH_CHANNEL_ID}
      - TWITCH_CHANNEL_NAME=${TWITCH_CHANNEL_NAME}
      - OPENROUTER_KEY=${OPENROUTER_KEY}
      - TOKEN_DB_PATH=/data/tokens.db
      - BOT_CONFIG_PATH=/config/bots.toml
    volumes:
      - tokens-data:/data
      - ./config:/config:ro
    depends_on:
      auth-server:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  tokens-data:
    driver: local