services:
  twitch-bot:
    build: .
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_CHANNEL_ID=${TWITCH_CHANNEL_ID}
      - TWITCH_CHANNEL_NAME=${TWITCH_CHANNEL_NAME}
      - OPENROUTER_KEY=${OPENROUTER_KEY}
      - TOKEN_JSON_PATH=/data/tokens.json
      - BOT_CONFIG_PATH=/config/bots.toml
    volumes:
      - bot-data:/data
      - ./config:/config:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Configuration Reload Instructions:
    # After editing config/bots.toml, reload without restart:
    #   docker compose kill -s HUP twitch-bot
    #
    # View reload status in logs:
    #   docker compose logs -f twitch-bot | grep -i config

volumes:
  bot-data:
    driver: local
