services:
  twitch-bot:
    image: ghcr.io/ikusner13/lonely-chat:latest
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - tokens-data:/data
      - ../files/bots.toml:/bots.toml:ro
      # Note: In Dokploy, use Advanced → Mounts → Add File Mount
      # 1. Go to Advanced → Mounts
      # 2. Create a new File Mount
      # 3. Name it: bots.toml
      # 4. Add your bots.toml content
      # The file will be created at /files/bots.toml and mounted to /bots.toml

  auth:
    image: ghcr.io/ikusner13/lonely-chat-auth:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - .env
    volumes:
      - tokens-data:/data

volumes:
  tokens-data:
    driver: local
