services:
  lonely-chat:
    image: ghcr.io/ikusner13/lonely-chat:latest
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - tokens-data:/data
      # set this in dokploy as a file mount
      - ../files/bots.toml:/bots.toml:ro
  lonely-chat-auth:
    image: ghcr.io/ikusner13/lonely-chat-auth:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - .env
    volumes:
      - tokens-data:/data

volumes:
  tokens-data:
    driver: local
