services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=twitch_bot
      - POSTGRES_USER=twitch_bot
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twitch_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-server:
    build: 
      context: .
      dockerfile: auth/Dockerfile
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_CHANNEL_ID=${TWITCH_CHANNEL_ID}
      - TWITCH_CHANNEL_NAME=${TWITCH_CHANNEL_NAME}
      - DATABASE_URL=postgresql://twitch_bot:${POSTGRES_PASSWORD}@postgres:5432/twitch_bot
      - TWITCH_REDIRECT_URI=${TWITCH_REDIRECT_URI}
      - PORT=8080
    volumes:
      - ./config:/config:ro
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  twitch-bot:
    build: .
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - TWITCH_CHANNEL_ID=${TWITCH_CHANNEL_ID}
      - TWITCH_CHANNEL_NAME=${TWITCH_CHANNEL_NAME}
      - OPENROUTER_KEY=${OPENROUTER_KEY}
      - DATABASE_URL=postgresql://twitch_bot:${POSTGRES_PASSWORD}@postgres:5432/twitch_bot
      - BOT_CONFIG_PATH=/config/bots.toml
    volumes:
      - ./config:/config:ro
    depends_on:
      postgres:
        condition: service_healthy
      auth-server:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres-data:
    driver: local